
language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install -g eslint
  - eslint . | tee eslint-output.txt
  - ./upload-eslint-results.sh ${SlackAPIToken} ${SlackBuildStatChannel}

script: npm test

notifications:
  slack: $SlackNotif



