
language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install -g eslint
  - eslint . | tee eslint-output.txt
  - TRAVIS_LINK = "https://travis-ci.com/Cyberunner23/SOEN343/builds/${TRAVIS_JOB_ID}"
  - curl -F file=@eslint-output.txt -F "initial_comment=Eslint output for build at ${TRAVIS_LINK}" -F channels=${SlackBuildStatChannel} -H "Authorization: Bearer ${SlackAPIToken}" https://slack.com/api/files.upload

script: npm test

notifications:
  slack: $SlackNotif



