language: node_js

addons:
  ssh_known_hosts: AlexFL.net

node_js:
  - "lts/*"

before_script:
  - npm install -g eslint
  - eslint . | tee eslint-output.txt
  - ./server_scripts/travis-upload-eslint-results.sh ${SlackAPIToken} ${SlackBuildStatChannel} ./eslint-output.txt

script: npm test


before_deploy:
  - openssl aes-256-cbc -K $encrypted_8f8918896de5_key -iv $encrypted_8f8918896de5_iv -in server_scripts/deploy_key.enc -out /tmp/deploy_key -d
  - echo -e "Host alexfl.net\n    StrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: ./server_scripts/travis-deploy.sh /tmp/deploy_key
  on:
    branch: master

notifications:
  slack:
    secure: S5UuG8DBmejPEI05HtpEZRyJ28ZFE9Zh71bkul8Enjqes9OSBjXY3ahqYGvec95ZN8/exwHNunl0tyf2KI9gsAvARruR2XZg2gcv/aonlTxW+jvDtLsSIN3lqVJkQKLl5mL6L75IOify9k62h9JNHKC6CeuYp8BW2mZ6FcddWwxRWyAfQakMVZvaQy7myG3WReOgfXeuZV9HxBtbKAriBQJfkmAwTHffpwLVJxhTP5EivjBJ/IfPLsc+KHjkTyBX4ZgShq+5SN6dGX/oSiacJyKcNpjN37arYCmimk8meK3u19EBaSwEjvdoCK7+40lTyzSMKQEnnVVNqZvGvrKSdYU4zDHj9xr0HDsoELWIWPohtczwA9FSP9hG1qVySFHmyxh0K1x9nXygtezCkgqr9+BeD7L/ZfH+aqLXIvFNcq1+E2SULNYXMLImlO2CpNKdq4f+wiw8Rq9zVcJRUB742P4kW8/sUGvX6IE4mXAHgxBnHuR0tgCXfpBKTs9CBZfZg87qTAOzwurFpvy+ftKTrwhJpaFN7Tbv54JvnoXP6G+YlVlOYqG3SumkaUwkJJpGI/Q2IMyvF4xY5owycMPAAOuhPW/LuwrZSpLcc0hk0hV1kYXNmDlcbziAAYEK1Rr/hqs9OdSdHDKlJ65Nu0tC0cx4H6vXKBqWGaO16rKTUvs=

